/subject, /exam, /question 라우트 추가
Double-Slash/5th-mini-team2 pull request #11
Opened 2020-09-27 05:17 UTC by TimeTREE98

/subject, /exam, /question 라우트 추가, 현재 문제 추가 지원 (그러나 사진 업로드 기능은 프론트와 기능 협의 필요함)

## 요약
문제 추가 기능을 추가하였습니다.

## 설명
Notion에 공유된 API 정의서 항목을 참고 부탁드립니다.

2020-09-27 08:55 UTC, kuk941025 requested changes
- 로컬에서 서버를 실행하려고 했는데 아래와 같은 오류가 발생했어요! ㅠㅠㅠㅠ 한번 확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/34362701/94360550-0ff49800-00e9-11eb-8664-f25f7c30b91e.png)

- model/mysql 폴더가 있는데 model 폴더 안에 있으니까 헷갈리는것같아요. model역할이 아닌것같아서요! model밖으로 위치를 옮기는건 어떨까요??

2020-09-27 08:55 UTC, kuk941025 commented on server/app.js
> +const etcRouter = require('./routes/etc');
etc말고 다른 이름을 사용하는건 어떨까요?? 이름만 봐서 무슨 역할을 하는 라우팅인지 잘 모르겠네요 😢

2020-09-27 08:55 UTC, kuk941025 commented on server/model/auth.js
>            }
if가 너무 많아서 코드읽기가 힘들어요..!
```javascript
if (compareSync)
 throw new Error()
if (U_FL === 'N') 
  throw new Error()
resolve()
```
형태로 수정해주시면 읽기 더 편할것같습니다.

2020-09-27 08:55 UTC, kuk941025 commented on server/model/etc.js
> +      const RE_S_SM = S_NM.replace(' ', '');  // 과목 이름에 공백 제거
과목사이에 있는 공백을 다 제거하려고 replace를 사용하신건가요?? replace를 사용하면 제일 앞에 있는 공백 하나만 제거됩니다🤔 
마지막 공백만 제거하려면 trim을 사용하는게 더 좋을것같아요!

2020-09-27 08:55 UTC, kuk941025 commented on server/model/etc.js
> +      const S_PK = uuid.generateConvert();
uuid를 바로 사용하지 않고 generateConvert를 사용하는 이유는 뭔가요?? 👀

2020-09-27 08:55 UTC, kuk941025 commented on server/model/question.js
> +            if (is.empty(Q.Q_SCORE)) throw new Error(`${Qindex + 1} 번의 Q_SCORE 항목이 없습니다.`);
현재 디자인에는 score 필드를 입력하는 항목이 없어요. 이 부분은 검사를 안해도 될것같습니다!

2020-09-27 08:55 UTC, kuk941025 commented on server/model/question.js
> +          await ArrayExt.asyncForEach(QUESTIONS, async (Q, Qindex, Qarr) => {
Questions를 forEach문을 돌고있는걸 알고있는데, Q, Qindex, Qarr를 사용하니까 개인적으로 Q가 너무 많이 들어간 느낌이 들어요ㅋㅋㅋ

2020-09-27 08:55 UTC, kuk941025 commented on server/model/question.js
> +        resolve({ 'status': 'success', 'msg': `${QUESTIONS.length} 문제 추가 성공했습니다.` });
궁금해서 질문드립니다! reject이 되고 나서 commit이 되도 괜찮은가요??

2020-09-28 17:47 UTC, TimeTREE98 commented on server/app.js
> +const etcRouter = require('./routes/etc');
API 정의성에 보시면 subject 라우트가 단 한두가지 기능만을 위해 존재하기에 한두가지로 동작하는 기능의 경우 etc로 추가하고 향후 스케일이 커질 경우 다시 재 작업 해둘 생각이여서 etc로 명명해두었습니다...!

2020-09-28 17:49 UTC, TimeTREE98 commented on server/model/etc.js
> +      const RE_S_SM = S_NM.replace(' ', '');  // 과목 이름에 공백 제거
아 모든 공백을 제거하기 위해서 정규식을 사용하는 것을 잠시 혼동하고있었습니다.
이 부분 replace(/ /g,'') 로 수정하겠습니다.

2020-09-28 17:59 UTC, TimeTREE98 commented on server/model/etc.js
> +      const RE_S_SM = S_NM.replace(' ', '');  // 과목 이름에 공백 제거
제가 왜 replace을 썻나 찾아보았는데   함수로 썻어도 됐습니다...

2020-09-28 18:00 UTC, TimeTREE98 commented on server/model/etc.js
> +      const S_PK = uuid.generateConvert();
해당 INSERT및 SELECT 문에 반영 안되어있어 현재 하이픈을 제거한 uuid가 저장되는 방식이지만
uuid가 생성될 경우 650772b8-a231-4ddc-ad6c-f4e8993089d3 이런 식으로 생성되는데, mysql의 연산 특성상, 문자셋 쿼리보단 바이너리 쿼리가 성능상 유리한 면이 있어 향후 Binary 컨버팅 버전으로 재 포팅 작업할 예정입니다!

2020-09-28 18:01 UTC, TimeTREE98 commented on server/model/question.js
> +            if (is.empty(Q.Q_SCORE)) throw new Error(`${Qindex + 1} 번의 Q_SCORE 항목이 없습니다.`);
해당 의견 반영하도록 하겠습니다!

2020-09-28 18:02 UTC, TimeTREE98 commented on server/model/question.js
> +          await ArrayExt.asyncForEach(QUESTIONS, async (Q, Qindex, Qarr) => {
사실 저 부분은 인덱스나 배열이 필요없으면 async (Q) => 형식으로 작업해도 되는 부분이여서 의견 반영하도록 하겠습니다.
저도 사실 저 부분이 조금 난잡해보이긴 하네요 ㅎㅎ

2020-09-28 18:03 UTC, TimeTREE98 commented
model/mysql 폴더에서 에러가 생기시는 이유는 .env 파일이 없어 환경 설정 변수를 불러오지 못해 생기는 에러입니다!
notion으로 .env 파일 공유해드리도록 하겠습니다!

2020-09-28 18:28 UTC, TimeTREE98 commented on server/model/question.js
> +        resolve({ 'status': 'success', 'msg': `${QUESTIONS.length} 문제 추가 성공했습니다.` });
해당 코드는 원래 정상적이라면 (beginTransaction) > A > B > C > (commit) 순으로 이어져가야하는데
A > B > C 쪽에서 문제가 생겨 도중에 rollback을 한 후, commit을 하게 되면 beginTransaction 이후 변경점 없이 commit을 함으로써 최종적으로 변경점 없이 트랜잭션 시작, 커밋으로 정상 종료되는 걸로 제가 알고 있어서 이와 같이 작성하였습니다.
혹시 제가 알고 있는 개념이 틀렸을까요?

2020-09-28 18:38 UTC, TimeTREE98 commented on server/model/auth.js
>            }
해당 의견 반영하도록 하겠습니다!

2020-09-29 08:37 UTC, kuk941025 commented on server/app.js
> +const etcRouter = require('./routes/etc');
아무리 기능이 적어도 etc라는 네이밍보다는 subject가 훨씬 좋을것같아요..!

2020-09-29 08:39 UTC, kuk941025 commented on server/model/question.js
> +        resolve({ 'status': 'success', 'msg': `${QUESTIONS.length} 문제 추가 성공했습니다.` });
문제가 전혀없군요! 아니요 그냥 궁금해서 질문드렸습니다😄😄

2020-09-29 08:40 UTC, kuk941025 commented
.env파일을 따로 윈도우에서 환경 변수로 설정해야 로컬에서 실행할 수 있는건가요???

2020-09-30 02:19 UTC, TimeTREE98 commented
윈도우 리눅스 상관없이 .env 파일을 서버 폴더내에 두기만 해도 될 것 입니다! (package.json와 동일 위치)
최종 파일 경로가 /server/.env 식으로 되면 됩니다!

2020-09-30 05:38 UTC, kuk941025 commented
앗 그러면 노션에 공유해주지 마시고 커밋에 포함시켜서 올려주실수 있을까요??

2020-10-06 08:48 UTC, kuk941025 approved these changes

2020-10-06 08:49 UTC, merged