객관식 문제 부분 추가
Double-Slash/5th-mini-team2 pull request #3
Opened 2020-09-16 11:00 UTC by InKyoJeong

## 요약

- 객관식 문제 추가하기 

## 설명

객관식 문제 추가하기랑 번호선택 하기 해봤습니다

2020-09-17 00:57 UTC, kuk941025 requested changes
빠르게 PR올려주셨네요👏👏👏
AnswerListItem이랑 AnswerList를 다른 파일로 분리해도 될것같아요.
그리고 css가 하나도 적용되지 않은것같은데 확인부탁드립니다!

2020-09-17 00:57 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +  const onInsert = useCallback(() => {
onInsert랑 onToggle에서 usecallback을 사용한 특별한 이유가 있을까요??

2020-09-17 00:57 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +      <div className="AnswerList">
camel case로 class 이름을 정하셨는데 class이름은 보통 하이픈 -을 사용해서 하기때문에 어색해보여요

2020-09-17 00:57 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +          {checked ? <i class="fas fa-circle"></i> : <i class="far fa-circle"></i>}
className으로 수정해줘야될것 같습니다!

2020-09-17 00:57 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +      <div className="AnswerListItem">
이 부분도 마찬가지로 하이픈 -을 사용해서 네이밍 수정해주세요~

2020-09-17 00:57 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +    <div className="answer-form">
answer-form이라는 class가 있나요??

2020-09-17 00:57 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +  ]);
프로젝트에서 AnserInput 컴포넌트를 사용할때 answers데이터와 이 데이터를 수정하는 setAnswers를 props로 보내줘야할것같은데, id를 가지고있는 데이터를 부모가 가지고있으면 불편할것 같다는 생각이 드네요..!

2020-09-18 21:26 UTC, InKyoJeong commented on web/src/components/AnswerInput.js
> +  const onInsert = useCallback(() => {
props로 전달해야할 함수를 만들때는 usecallback으로 감싸는게 좋다고 봐서 썼는데 안해도 상관없나요??

2020-09-18 21:29 UTC, InKyoJeong commented on web/src/components/AnswerInput.js
> +    <div className="answer-form">
이거 그냥 나중에 css적용하기위해 네이밍을 한건데 class가 있나요?가 무슨 말씀이신지 잘모르겠어요

2020-09-20 05:24 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +    <div className="answer-form">
answer-form이라는 css가 안보여서 물어본거였어요. css는 언제 적용하실수 있을까요??

2020-09-20 06:52 UTC, InKyoJeong commented on web/src/components/AnswerInput.js
> +    <div className="answer-form">
아아 적용해볼게요~

2020-09-20 06:55 UTC, InKyoJeong commented on web/src/components/AnswerInput.js
> +  ]);
id를 가지고있는 데이터를 부모가 가지고있으면 불편하다는거 잘 이해가안되는데 좀 쉽게설명해주실수있나요? 제가 코드리뷰도 처음이고 아직 많이 부족해서 어렵네요

2020-09-20 07:03 UTC, InKyoJeong commented on web/src/components/AnswerInput.js
> +  ]);
id를 가지고있는 데이터를 부모가 가지고있으면 불편할것같다는거 잘 이해가안되는데 좀 쉽게설명해주실수있나요? 그럼 어떻게 작성해야할까요? 제가 코드리뷰도 처음이고 아직 많이 부족해서 좀 어렵네요

2020-09-20 07:11 UTC, jaykay-p commented on web/src/components/AnswerInput.js
> +  const onInsert = useCallback(() => {
제 생각에는 큰 차이가 없을것같아 보여서 궁금해서 물어봤습니다! 정상적으로 잘 작동이되면 상관없을것같아요

2020-09-20 07:32 UTC, kuk941025 commented on web/src/components/AnswerInput.js
> +  ]);
AnswerInput을 사용하는 부모 컴포넌트로 예시코드를 작성해보겠습니다!

```javascript
const Main = () => {
  const [answerList, setAnswerList] = useState([
    [false, false, true, true, false],
    [false, false, false, false, true]
  ])

  const handleAnswers = (idx) => {
    // answers 수정
  }
  return (
    <div>
      <AnswerInput answers={answerList[0]} setAnswers={handleAnswers} />
      <AnswerInput answers={answerList[1]} setAnswers={handleAnswers} />
    </div>
  );
};
```
이때 부모가 id값을 안가지고 있는게 더 AnswerInput 컴포넌트 사용할때 편할것 같아보여요.
AnswerInput 컴포넌트에서 key 값이 필요하면 map의 두번째 인자인 idx를 사용하거나 `uuid` 라이브러리를 사용하면 될것같아요

2020-09-21 13:26 UTC, kuk941025 approved these changes

2020-09-21 13:27 UTC, merged