Feature/create link
Double-Slash/5th-mini-team2 pull request #4
Opened 2020-09-19 06:22 UTC by healing99

## 요약
문제 제작 페이지의 상단에 들어갈 입력창
## 설명
실제 추가 및 수정한 부분은 createLink.js 와 Create.js 그리고 App.js 입니다!
-bootstrap의 기본 navbar를 활용함  
-기본적인 style은 `<style jsx>` 태그 사용   
-시간입력은 숫자만 입력 가능  
-링크생성 버튼 클릭 시 콘솔창에서 값 확인 가능  
-한 입력칸이라도 빈 상태로 제출 시 alert창  

부족한 부분이 많지만 보시고 피드백 해주시면 감사하겠습니다 !!!

2020-09-20 05:20 UTC, kuk941025 requested changes
수고하셨습니다👍
다음에는 커밋 메세지를 추가하는 기능에 맞게 메세지를 작성해주시면 좋을것같아요. 커멘트 단 부분 확인부탁드릴게요😃

2020-09-20 05:20 UTC, kuk941025 commented on web/src/components/CreateLink.js
> +    const re = /^[0-9\b]+$/;
input의 type을 number로 설정하면, 정규식없이 숫자만 입력받을수 있습니다!

2020-09-20 05:20 UTC, kuk941025 commented on web/src/components/CreateLink.js
> +    if (`${lecture}` == '' || `${subject}` == '' || `${time}` == '') {
===를 사용해서 lecture === ''로 작성하는게 더 보기 좋을것같아요

2020-09-20 05:20 UTC, kuk941025 commented on web/src/components/CreateLink.js
> +    document.getElementById('myButton').blur();
리액트에서 dom을 참조할때는 ref를 사용하는 방법이 권장됩니다. 함수형 컴포넌트니까 useRef를 사용해주세요!
그리고 dom id를 myButton보다는 버튼 역할에 어울리는 id로 수정해주세요

2020-09-20 05:20 UTC, kuk941025 commented on web/src/components/CreateLink.js
> +  const onReset = () => {
앞에 on이 있으면 event에 맞게 실행되는 함수처럼 보여요. resetInputs 로 변경하면 더 읽기 쉬울것같습니다

2020-09-20 05:20 UTC, kuk941025 commented on web/src/pages/Create.js
> +      <CreateLink></CreateLink>
CreateLink에 children이 없으면 <CreateLink /> 만 사용하셔도 됩니다

2020-09-20 05:20 UTC, kuk941025 commented on web/src/components/CreateLink.js
> +          }
first, second, third로 네이밍을 해주셨는데, textField에 어울리는 네이밍을 하는 방법이 더 좋아보여요. 아니면 css의 :nth-child를 사용하는 방법을 추천합니다.
https://developer.mozilla.org/ko/docs/Web/CSS/:nth-child

2020-09-21 08:56 UTC, healing99 commented on web/src/components/CreateLink.js
> +          }
말씀해주신대로 nth-child를 사용해보려고
input : nth-child(1) 이런식으로 작성했는데 적용이 잘 안되네요,,

2020-09-21 09:09 UTC, kuk941025 commented on web/src/components/CreateLink.js
> +          }
네 그럼 first, second, third를 textfield에 맞게 변경만해주세요!

2020-09-21 09:11 UTC, healing99 commented on web/src/components/CreateLink.js
> +          }
네 !

2020-09-21 09:41 UTC, kuk941025 approved these changes

2020-09-21 09:42 UTC, merged