Feature/question radio
Double-Slash/5th-mini-team2 pull request #5
Opened 2020-09-20 16:06 UTC by HyunaKim10

## 요약
문제유형선택토글 컴포넌트.
css를 적용해야되는 경우 styles-jsx를 사용

## 설명
- [x ]  버튼 하나를 선택할 수 있어야 한다.
- [x ]  이미지를 추가할 수 있다.

2020-09-21 06:09 UTC, kuk941025 requested changes
useState을 사용하는 부분이 조금 어색해보이는것을 제외하면 잘 만들어주신 것 같아요 👍 
고생하셨어요 커멘트 단 부분 확인부탁드립니다!

2020-09-21 06:09 UTC, jaykay-p commented on web/src/components/QuestionRadio.js
> +  const [state, setState] = useState({
state이라는 이름을 보면 데이터가 어떤 역할을 하는지 알기가 힘들어요..! 
`[radioGroup, setRadioGroup]` 으로 수정하는게 더 나아보여요

2020-09-21 06:09 UTC, jaykay-p commented on web/src/components/QuestionRadio.js
> +    },
radioGroup 객체를 따로 만들필요가 없어보여요🤔
`
useState({
  multipleChoice: false, narrative: true, shortAnswer: false
})
` 로도 가능하지 않을까요??

2020-09-21 06:09 UTC, kuk941025 commented on web/src/components/QuestionRadio.js
> +    setState({ radioGroup: obj });
토글 버튼을 클릭할때마다 새로운 객체를 만들면, 새롭게 생성되는 객체의 값은 클릭한 버튼 값만 들어가게돼요. 
multipleChoice버튼을 클릭하면 `{multipleChoice: true}`인 객체가 생성되고 narrative, shortAnswer의 값은 들어가지 않아서 경고 메세지가 뜰것같아요.
그리고 event.target.value 값을 사용하는것보다 name을 사용하는게 더 어울려 보여요.
`
setRadioGroup({
  ..radioGroup,
  [event.target.name]: event.target.checked
})
` 처럼 처리하는게 좋아보입니다. 근데, 토글 버튼은 하나만 활성화를 할수있으니까 클릭한 토글 버튼외에는 다 false 값이 들어가면 될것같네요😃

2020-09-21 06:09 UTC, kuk941025 commented on web/src/components/QuestionRadio.js
> +          value="multipleChoice"
위에도 업급했지만 name을 multipleChoice하는게 좋아보입니다!

2020-09-21 06:09 UTC, kuk941025 commented on web/src/components/QuestionRadio.js
> +          <img src="check_on.png" width="20" />
png파일은 추가해주지 않으셔서 이미지를 확인할수가 없네요ㅠㅜ

2020-09-21 15:09 UTC, HyunaKim10 commented on web/src/components/QuestionRadio.js
> +          <img src="check_on.png" width="20" />
저 파일이 제가 가진 임시파일이라서 디자인 나오면 넣으면 될거 같아 따로 파일 추가는 하지 않았습니다!

2020-09-22 03:09 UTC, kuk941025 approved these changes

2020-09-22 03:09 UTC, merged